spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 7845
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database: memory